name: healthkit-backend
services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
      repo: your-username/HealthKit_Backend
    build_command: pip install -r requirements.txt
    run_command: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: MONGODB_URL
        scope: RUN_AND_BUILD_TIME
        value: ${mongodb.MONGODB_URL}
      - key: REDIS_URL
        scope: RUN_AND_BUILD_TIME
        value: ${redis.REDIS_URL}
      - key: GOOGLE_SHEETS_CREDENTIALS
        scope: RUN_AND_BUILD_TIME
        value: ${GOOGLE_SHEETS_CREDENTIALS}
      - key: GOOGLE_SHEETS_ID
        scope: RUN_AND_BUILD_TIME
        value: ${GOOGLE_SHEETS_ID}

databases:
  - engine: MONGODB
    name: mongodb
    production: false
    cluster_name: healthkit-mongodb
    db_name: healthkit
    db_user: healthkit_user

  - engine: REDIS
    name: redis
    production: false
    cluster_name: healthkit-redis 