name: healthkit-backend
region: sgp
services:
  - name: api
    git:
      branch: master
      repo_clone_url: https://github.com/moovingsloth/healthkit_backend
    build_command: pip install -r requirements.txt
    environment_slug: python
    instance_size_slug: basic-xs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: MONGODB_URL
        scope: RUN_TIME
        value: ${healthkit-mongodb.DATABASE_URL}
      - key: REDIS_URL
        scope: RUN_TIME
        value: ${healthkit-redis.DATABASE_URL}
      - key: MODEL_PATH
        scope: RUN_TIME
        value: model/concentration_model.pkl
      - key: GOOGLE_SHEETS_ID
        scope: RUN_TIME
        value: ""

databases:
  - engine: MONGODB
    name: healthkit-mongodb
    production: false
    cluster_name: healthkit-mongodb
    db_name: healthkit
    db_user: healthkit_user

  - engine: REDIS
    name: healthkit-redis
    production: false
    cluster_name: healthkit-redis