name: Deploy to Digital Ocean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Digital Ocean Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/your-registry/healthkit-backend:latest

      - name: Deploy to Digital Ocean App Platform
        uses: digitalocean/app_action@v1
        with:
          app_name: healthkit-backend
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: |
            [
              {
                "name": "healthkit-backend",
                "registry_type": "DOCR",
                "registry": "registry.digitalocean.com",
                "repository": "your-registry/healthkit-backend",
                "tag": "latest"
              }
            ] 